// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.tencent.tmm.pbservice.export.protocol.EmptyResponse in service/empty_rpc.proto
package com.tencent.tmm.pbservice.export.protocol

import com.squareup.wire.kmm.FieldEncoding
import com.squareup.wire.kmm.Message
import com.squareup.wire.kmm.ProtoAdapter
import com.squareup.wire.kmm.ProtoReader
import com.squareup.wire.kmm.ProtoWriter
import com.squareup.wire.kmm.ReverseProtoWriter
import com.squareup.wire.kmm.Syntax.PROTO_3
import okio.ByteString
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField

public class EmptyResponse(
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<EmptyResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is EmptyResponse) return false
    if (unknownFields != other.unknownFields) return false
    return true
  }

  public override fun hashCode(): Int = unknownFields.hashCode()

  public override fun toString(): String = "EmptyResponse{}"

  public fun copy(unknownFields: ByteString = this.unknownFields): EmptyResponse =
      EmptyResponse(unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<EmptyResponse> = object : ProtoAdapter<EmptyResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      EmptyResponse::class,
      "type.googleapis.com/com.tencent.tmm.pbservice.export.protocol.EmptyResponse",
      PROTO_3, 
      null
    ) {
      public override fun encodedSize(`value`: EmptyResponse): Int {
        var size = value.unknownFields.size
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: EmptyResponse): Unit {
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: EmptyResponse): Unit {
        writer.writeBytes(value.unknownFields)
      }

      public override fun decode(reader: ProtoReader): EmptyResponse {
        val unknownFields = reader.forEachTag(reader::readUnknownField)
        return EmptyResponse(
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: EmptyResponse): EmptyResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
