source "https://git.woa.com/TencentVideoShared/VideoBase.git"
source "https://git.woa.com/TencentVideoShared/VideoBase-snapshot.git"
source "https://mirrors.tencent.com/repository/generic/pod-go/T-CocoaPods/Specs/"

target 'iosApp' do
  use_frameworks! :linkage => :static
  platform :ios, '12.0'

  # 注意: 必须先执行 gradle‘podPublishXCFramework’,检查目录下已有framework产物再打开此行，执行pod install后调试iOS App
#   pod 'shared_template', :path => '../shared-template/build/cocoapods/publish/debug'

#   pod 'VBTransportServiceiOS', '6.1.0'
  pod 'VBTransportServiceiOS', :git => 'https://git.woa.com/NextLib/VBTransportServiceiOS.git', :branch => 'feature/sse_log'

  pod 'VBKVServiceiOS', '2.6.3'
  pod 'MMKVCore', '1.3.2'
  pod 'VBMMKV', '1.3.2'
  pod 'TQUICiOS', '1.5.3'
  pod 'VBTQUIC', '2.2.9'
  pod 'VBAFNHttpDataRequest', '2.15.1'
  pod 'VBLogServiceiOS', '0.0.48'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings["ARCHS[sdk=iphonesimulator*]"] = "x86_64" #模拟器使用x86_64,M1电脑就可以用模拟器了
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Tencent"
end
