source "https://git.woa.com/TencentVideoShared/VideoBase.git"
source "https://git.woa.com/TencentVideoShared/VideoBase-snapshot.git"
source "https://mirrors.tencent.com/repository/generic/pod-go/T-CocoaPods/Specs/"

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'shared_template', :path => '../shared-template'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 升级下依赖的部署版本
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
